#!/bin/sh

# Thin wrapper: we run `git pull`, which may modify other files in the
# repository. We assume it won't modify *this* file, because this file is so
# simple.

DIRNAME="$(dirname "$0")"

. "$DIRNAME"/common.sh

echo "Updating overview-local repository..."
(cd "$DIRNAME" && git pull -q --rebase)

exec "$DIRNAME"/start-after-git-pull
