#!/bin/sh

DIRNAME="$(dirname "$0")"
CONFIG="$(dirname "$0")"/config

NETWORK="overviewlocal_default"

. "$DIRNAME"/common.sh

[ -f "$CONFIG"/overview.env ] || echo '# You may edit this file. Read overview.defaults.env for options.' > "$CONFIG"/overview.env

. "$DIRNAME"/lib/upgrade-obsolete-volumes.sh
migrate_volumes_if_needed

echo "Launching database..."
$DOCKER_COMPOSE up -d overview-database
# Gotta use "sh", not "/bin/sh", or Windows 10 gives error:
# stat: C:/Program Files/Git/usr/bin/sh: no such file or directory
docker run \
  --net "$NETWORK" \
  --rm "$BUSYBOX_IMAGE" \
  sh -c 'until $(nc overview-database 5432 2>/dev/null); do sleep 1; done'

echo "Applying latest schema..."
docker run \
  --net "$NETWORK" \
  --env-file "$CONFIG"/overview.defaults.env \
  --env-file "$CONFIG"/overview.env \
  --rm overview/db-evolution-applier

echo "Launching Overview..."
$DOCKER_COMPOSE up -d

GATEWAY_HOST=$(test $OVERVIEW_ADDRESS && echo $OVERVIEW_ADDRESS || docker-machine ip default 2>/dev/null || docker network inspect "$NETWORK" -f '{{range .IPAM.Config}}{{.Gateway}}{{end}}')

link_plugins() {
  echo "Linking plugins to Overview at $GATEWAY_HOST..."
  docker run \
    --env "DOCKER_HOST=$GATEWAY_HOST" \
    --net "$NETWORK" \
    --rm overview/plugin-setup
}
grep --silent '^SKIP_PLUGIN_SETUP=true$' config/overview.env || link_plugins

echo "Waiting for everything to come online..."
# Wait for the server to start
docker run \
  --net "$NETWORK" \
  --rm "$BUSYBOX_IMAGE" \
  sh -c 'until $(nc overview-web 9000 2>/dev/null); do sleep 1; done'

echo
echo "Overview is running: browse to http://$GATEWAY_HOST:9000 to use it"
