#!/bin/sh

. "$(dirname "$0")"/common.sh

ALL="overview-database overview-redis overview-searchindex overview-documentset-worker overview-worker overview-web overview-word-cloud overview-entity-filter overview-grep overview-file-browser overview-multi-search"

for service in $ALL; do
  docker logs --follow $service | sed -e "s/^/[$service] /" &
done

sleep 999999999999
