#!/bin/sh

. "$(dirname "$0")"/common.sh

docker pull "$BUSYBOX_IMAGE"
docker pull "$UBUNTU_IMAGE"
docker pull overview/overview-proxy:latest # TODO use version number
$DOCKER_COMPOSE pull --parallel
