#!/bin/bash

. "$(dirname "$0")"/common.sh
CONFIG="$(dirname "$0")"/config

docker-compose -f "$CONFIG"/services.yml pull
docker-compose -f "$CONFIG"/overview.yml pull
docker-compose -f "$CONFIG"/plugins.yml pull
docker pull overview/db-evolution-applier
docker pull overview/plugin-setup
